USE conta;

DROP TABLE IF EXISTS `accountchart`;
CREATE TABLE `accountchart` (
  `ENCODEDKEY` varchar(45) NOT NULL,
  `ACCOUNTCHARTID` varchar(45) DEFAULT NULL,
  `GLCODE` varchar(45) DEFAULT NULL,
  `GLNAME` varchar(45) DEFAULT NULL,
  `TYPE` varchar(45) DEFAULT NULL,
  `OWNER` varchar(45) DEFAULT NULL,
  `ENABLE` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ENCODEDKEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `accountingbalancestage3`;
CREATE TABLE `accountingbalancestage3` (
  `LOANID` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `var_INTEREST_S3` decimal(50,2) DEFAULT NULL,
  `var_INTEREST_MA` decimal(50,2) DEFAULT NULL,
  `var_PENALTY_S3` decimal(50,2) DEFAULT NULL,
  `var_PENALTY_MA` decimal(50,2) DEFAULT NULL,
  `CREATIONDATE` datetime NOT NULL,
  PRIMARY KEY (`LOANID`,`CREATIONDATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `accountinghubentry`;
CREATE TABLE `accountinghubentry` (
  `LOANID` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `PRODUCTENCODEDKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL DEFAULT '',
  `BRANCHNAME` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ACTUALSTAGE` text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `LASTSTAGECHANGE` text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `GLCODE` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `GLNAME` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL DEFAULT '',
  `TRANSACTIONID` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `ENTRYID` bigint NOT NULL DEFAULT '0',
  `AMOUNT` decimal(43,2) NOT NULL DEFAULT '0.00',
  `CREATIONDATE` datetime NOT NULL,
  `BookingDATE` datetime DEFAULT NULL,
  `TYPE` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL DEFAULT '',
  `LOANTRANSACTIONTYPE` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `PRINCIPALDUE` decimal(43,2) DEFAULT NULL,
  `PRICINPALBALANCE` decimal(43,2) DEFAULT NULL,
  `REVERSALTRANSACTIONID` varchar(32) DEFAULT NULL,
  `IS_PAYOFF` tinyint(1) NOT NULL DEFAULT '0',
  `IS_PREPAYMENT` tinyint(1) NOT NULL DEFAULT '0',
  `IS_OVERDUE` tinyint(1) NOT NULL DEFAULT '0',
  `TRANSACTIONCHANNEL` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`LOANID`,`ENTRYID`),
  KEY `idx_rpaoriginal_CREATIONDATE` (`CREATIONDATE`),
  KEY `idx_rpaoriginal_REVERSALTRANSACTIONID` (`REVERSALTRANSACTIONID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `accountinghubexit`;
CREATE TABLE `accountinghubexit` (
  `LOANID` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `PRODUCTENCODEDKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL DEFAULT '',
  `BRANCHNAME` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ACTUALSTAGE` text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `LASTSTAGECHANGE` text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `GLCODE` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `GLNAME` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL DEFAULT '',
  `TRANSACTIONID` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `ENTRYID` bigint NOT NULL DEFAULT '0',
  `TRANSACTIONIDREV` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '',
  `ENTRYIDREV` bigint DEFAULT '0',
  `AMOUNT` decimal(50,2) DEFAULT NULL,
  `CREATIONDATE` datetime DEFAULT NULL,
  `BookingDATE` datetime DEFAULT NULL,
  `TYPE` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL DEFAULT '',
  `LOANTRANSACTIONTYPE` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `MAMBUGLCODE` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`LOANID`,`GLCODE`,`TRANSACTIONID`,`ENTRYID`,`TYPE`),
  KEY `idx_rpatransformado_LOANID_GLCODE_ENTRYID_CREATIONDATE_TYPE` (`LOANID`,`GLCODE`,`ENTRYID`,`CREATIONDATE`,`TYPE`),
  KEY `idx_rpatransformado_TRANSACTIONID_MAMBUGLCODE` (`MAMBUGLCODE`,`TRANSACTIONID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `accountinghublogs`;
CREATE TABLE `accountinghublogs` (
  `LOGID` int NOT NULL AUTO_INCREMENT,
  `LOGLINE` varchar(120) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `CREATIONDATE` datetime NOT NULL,
  PRIMARY KEY (`LOGID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `accountinghubprocesscontrol`;
CREATE TABLE `accountinghubprocesscontrol` (
  `PROCESSUUID` varchar(45) NOT NULL,
  `STARTDATE` datetime DEFAULT NULL,
  `ENDDATE` datetime DEFAULT NULL,
  `CURRENTSTEP` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`PROCESSUUID`),
  KEY `STARTDATE_IDX` (`STARTDATE`),
  KEY `STATUS_IDX` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `configurationaccountinghub`;
CREATE TABLE `configurationaccountinghub` (
  `ENCODEDKEY` varchar(45) NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `VALUECONFIGURATION` varchar(500) DEFAULT NULL,
  `ENABLE` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ENCODEDKEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `configurationsheetcolumns`;
CREATE TABLE `configurationsheetcolumns` (
  `ENCODEDKEY` varchar(45) NOT NULL,
  `CONFIGURATIONSHEETENCODEDKEY` varchar(45) NOT NULL,
  `NAME` varchar(45) DEFAULT NULL,
  `COLUMNINDEX` int DEFAULT NULL,
  `REQUIRED` tinyint(1) DEFAULT NULL,
  `ENABLE` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ENCODEDKEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `configurationsheets`;
CREATE TABLE `configurationsheets` (
  `ENCODEDKEY` varchar(45) NOT NULL,
  `NAME` varchar(45) DEFAULT NULL,
  `STARTPOSITION` int DEFAULT NULL,
  `STARTPOSITIONCOLUMNNAME` int DEFAULT NULL,
  `NUMBERCOLUMNS` int DEFAULT NULL,
  `REQUIREDID` tinyint(1) DEFAULT NULL,
  `STARTPOSITIONID` int DEFAULT NULL,
  `RECLASSIFICATION` tinyint(1) DEFAULT NULL,
  `ENABLE` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ENCODEDKEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `loanaccounthistory`;
CREATE TABLE `loanaccounthistory` (
  `ENCODEDKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
  `ACCOUNTHOLDERKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
  `ACCOUNTHOLDERTYPE` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
  `ACCOUNTSTATE` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ACCOUNTSUBSTATE` varchar(256) DEFAULT NULL,
  `RESCHEDULEDACCOUNTKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ASSIGNEDBRANCHKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ASSIGNEDUSERKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `CLOSEDDATE` datetime DEFAULT NULL,
  `LASTLOCKEDDATE` datetime DEFAULT NULL,
  `CREATIONDATE` datetime DEFAULT NULL,
  `APPROVEDDATE` datetime DEFAULT NULL,
  `FEESDUE` decimal(50,10) DEFAULT NULL,
  `FEESPAID` decimal(50,10) DEFAULT NULL,
  `GRACEPERIOD` int NOT NULL,
  `GRACEPERIODTYPE` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ID` varchar(32) DEFAULT NULL,
  `INTERESTCALCULATIONMETHOD` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `INTERESTTYPE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT 'SIMPLE_INTEREST',
  `REPAYMENTSCHEDULEMETHOD` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `INTERESTAPPLICATIONMETHOD` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `PAYMENTMETHOD` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `INTERESTCHARGEFREQUENCY` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `INTERESTBALANCE` decimal(50,10) DEFAULT NULL,
  `INTERESTPAID` decimal(50,10) DEFAULT NULL,
  `INTERESTRATE` decimal(50,20) DEFAULT NULL,
  `LASTMODIFIEDDATE` datetime DEFAULT NULL,
  `LASTSETTOARREARSDATE` datetime DEFAULT NULL,
  `LOANAMOUNT` decimal(50,10) DEFAULT NULL,
  `PERIODICPAYMENT` decimal(50,10) NOT NULL DEFAULT '0.0000000000',
  `LOANGROUP_ENCODEDKEY_OID` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `LOANNAME` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `NOTES` mediumtext,
  `PENALTYDUE` decimal(50,10) DEFAULT NULL,
  `PENALTYPAID` decimal(50,10) DEFAULT NULL,
  `PRINCIPALBALANCE` decimal(50,10) DEFAULT NULL,
  `PRINCIPALPAID` decimal(50,10) DEFAULT NULL,
  `PRODUCTTYPEKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `REPAYMENTINSTALLMENTS` int NOT NULL,
  `REPAYMENTPERIODCOUNT` int DEFAULT NULL,
  `REPAYMENTPERIODUNIT` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ACCOUNTS_INTEGER_IDX` int DEFAULT NULL,
  `MIGRATIONEVENTKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ASSIGNEDCENTREKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `LASTACCOUNTAPPRAISALDATE` datetime DEFAULT NULL,
  `PRINCIPALREPAYMENTINTERVAL` int DEFAULT '1',
  `PRINCIPALDUE` decimal(50,10) DEFAULT NULL,
  `INTERESTDUE` decimal(50,10) DEFAULT NULL,
  `LASTINTERESTREVIEWDATE` datetime DEFAULT NULL,
  `ACCRUELATEINTEREST` bit(1) NOT NULL DEFAULT b'1',
  `INTERESTSPREAD` decimal(50,10) DEFAULT NULL,
  `INTERESTRATESOURCE` varchar(256) NOT NULL DEFAULT 'FIXED_INTEREST_RATE',
  `INTERESTRATEREVIEWUNIT` varchar(256) DEFAULT NULL,
  `INTERESTRATEREVIEWCOUNT` int DEFAULT NULL,
  `ACCRUEDINTEREST` decimal(50,10) DEFAULT '0.0000000000',
  `LASTINTERESTAPPLIEDDATE` datetime DEFAULT NULL,
  `FEESBALANCE` decimal(50,10) DEFAULT '0.0000000000',
  `PENALTYBALANCE` decimal(50,10) DEFAULT '0.0000000000',
  `SCHEDULEDUEDATESMETHOD` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL DEFAULT 'INTERVAL',
  `HASCUSTOMSCHEDULE` bit(1) NOT NULL DEFAULT b'0',
  `FIXEDDAYSOFMONTH` mediumblob,
  `SHORTMONTHHANDLINGMETHOD` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `TAXRATE` decimal(50,10) DEFAULT NULL,
  `LASTTAXRATEREVIEWDATE` datetime DEFAULT NULL,
  `PENALTYRATE` decimal(50,20) DEFAULT NULL,
  `LOANPENALTYCALCULATIONMETHOD` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT 'NONE',
  `ACCRUEDPENALTY` decimal(50,10) DEFAULT '0.0000000000',
  `ACTIVATIONTRANSACTIONKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `LINEOFCREDITKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `LOCKEDOPERATIONS` mediumblob,
  `INTERESTCOMMISSION` decimal(50,20) DEFAULT NULL,
  `DEFAULTFIRSTREPAYMENTDUEDATEOFFSET` decimal(50,20) DEFAULT NULL,
  `PRINCIPALPAYMENTSETTINGSKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `INTERESTBALANCECALCULATIONMETHOD` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT 'PRINCIPAL_ONLY',
  `DISBURSEMENTDETAILSKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ARREARSTOLERANCEPERIOD` int NOT NULL DEFAULT '0',
  `ACCRUEINTERESTAFTERMATURITY` bit(1) NOT NULL DEFAULT b'0',
  `PREPAYMENTRECALCULATIONMETHOD` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `PRINCIPALPAIDINSTALLMENTSTATUS` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ELEMENTSRECALCULATIONMETHOD` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `LATEPAYMENTSRECALCULATIONMETHOD` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `APPLYINTERESTONPREPAYMENTMETHOD` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `ALLOWOFFSET` bit(1) NOT NULL DEFAULT b'0',
  `FUTUREPAYMENTSACCEPTANCE` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL DEFAULT 'NO_FUTURE_PAYMENTS',
  `REDRAWBALANCE` decimal(50,10) DEFAULT NULL,
  `PREPAYMENTACCEPTANCE` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT 'ACCEPT_PREPAYMENTS',
  `INTERESTFROMARREARSACCRUED` decimal(50,10) DEFAULT '0.0000000000',
  `INTERESTFROMARREARSDUE` decimal(50,10) DEFAULT '0.0000000000',
  `INTERESTFROMARREARSPAID` decimal(50,10) DEFAULT '0.0000000000',
  `INTERESTFROMARREARSBALANCE` decimal(50,10) DEFAULT '0.0000000000',
  `INTERESTROUNDINGVERSION` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT 'VERSION_1',
  `ACCOUNTARREARSSETTINGSKEY` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `HOLDBALANCE` decimal(50,10) NOT NULL DEFAULT '0.0000000000',
  `SNAPSHOTDATE` date NOT NULL DEFAULT (curdate()),
  PRIMARY KEY (`ENCODEDKEY`,`SNAPSHOTDATE`),
  UNIQUE KEY `LOANACCOUNT_ID_SNAPSHOTDATE` (`ID`,`SNAPSHOTDATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


DROP TABLE IF EXISTS `productaccountinghub`;
CREATE TABLE `productaccountinghub` (
  `PRODUCTENCODEDKEY` varchar(45) NOT NULL,
  `PRODUCTID` varchar(45) DEFAULT NULL,
  `ACCOUNTCHART` varchar(45) DEFAULT NULL,
  `ENABLE` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`PRODUCTENCODEDKEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `sheetparametrization`;
CREATE TABLE `sheetparametrization` (
  `ENCODEDKEY` varchar(45) NOT NULL,
  `ACCOUNTCHART` varchar(45) DEFAULT NULL COMMENT 'ACCOUNTCHART',
  `CREATIONDATE` datetime DEFAULT NULL,
  `CURRENTSTAGE` varchar(45) DEFAULT NULL,
  `CURRENTGLCODE` varchar(45) DEFAULT NULL,
  `CURRENTLOANTRXTYPE` varchar(45) DEFAULT NULL,
  `CURRENTJETYPE` varchar(45) DEFAULT NULL,
  `OUTPUTGLCODE` varchar(45) DEFAULT NULL,
  `OUTPUTGLNAME` varchar(100) DEFAULT NULL,
  `OUTPUTJETYPE` varchar(45) DEFAULT NULL,
  `EXCLUSIONGLCODES` varchar(500) DEFAULT NULL,
  `ADJUST` tinyint(1) NOT NULL DEFAULT '0',
  `OBSERVACIONES` varchar(5000) DEFAULT NULL,
  `ENABLE` tinyint(1) NOT NULL DEFAULT '0',
  `TAXENTRY` tinyint(1) NOT NULL DEFAULT '0',
  `PRINCIPAL` tinyint(1) NOT NULL DEFAULT '0',
  `OVERDUEPPAL` tinyint(1) NOT NULL DEFAULT '0',
  `ORDERACCOUNT` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ENCODEDKEY`),
  KEY `idx_sheetparametrization_STAGE_GLCODE_LOANTX` (`CURRENTSTAGE`,`CURRENTGLCODE`,`CURRENTLOANTRXTYPE`),
  KEY `idx_sheetparametrization_STAGE_GLCODE_LOANTX_JETYPE` (`CURRENTSTAGE`,`CURRENTGLCODE`,`CURRENTLOANTRXTYPE`,`CURRENTJETYPE`),
  KEY `idx_sheetparametrization_STAGE_LOANTX_JETYPE` (`CURRENTSTAGE`,`CURRENTLOANTRXTYPE`,`CURRENTJETYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;