name: DB DDL AND INITIAL SETUP

on:
  pull_request:
    branches:
      - main
    paths:
      - 'UalaAccounting/UalaAccounting.dll/**'
      - 'UalaAccounting/UalaAccounting.setup/**'
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub Actions  

jobs:
  run-mysql-scripts:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install MySQL Client
      run: sudo apt-get update && sudo apt-get install -y mysql-client
        
    - name: Run MySQL scripts
      run: |
        mysql -h "${{ secrets.DB_HOST }}" -u "${{ secrets.DB_USER }}" -p"${{ secrets.DB_PASSWORD}}" "${{ secrets.DB_NAME }}" < "UalaAccounting/UalaAccounting.ddl/0001 schema.sql"
        mysql -h "${{ secrets.DB_HOST }}" -u "${{ secrets.DB_USER }}" -p"${{ secrets.DB_PASSWORD}}" "${{ secrets.DB_NAME }}" < "UalaAccounting/UalaAccounting.setup/0001 insert setup.sql"
    - name: Clean up
      run: |
        echo "Cleaning up..."